from __future__ import annotations

import json
import re
import secrets
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable
from urllib.parse import quote

from .crypto import RealityCredentials, generate_reality_credentials
from .model import Topology


@dataclass(slots=True)
class Listener:
    server: str
    port: int
    route_index: int
    hop_index: int
    source: str
    transport: str
    credentials: RealityCredentials
    sni: str
    xhttp_path: str
    ss_password: str


class PortAllocator:
    def __init__(
        self,
        pool: list[int],
        occupied: dict[str, set[int]] | None = None,
        preferred: dict[str, list[int]] | None = None,
    ) -> None:
        self.pool = list(pool)
        self.used: dict[str, set[int]] = {k: set(v) for k, v in (occupied or {}).items()}
        self.preferred: dict[str, list[int]] = {k: list(v) for k, v in (preferred or {}).items()}

    def alloc(self, server: str) -> int:
        used = self.used.setdefault(server, set())
        preferred = self.preferred.setdefault(server, [])
        while preferred:
            port = int(preferred.pop(0))
            if port in self.pool and port not in used:
                used.add(port)
                return port
        for port in self.pool:
            if port not in used:
                used.add(port)
                return port
        free = [p for p in self.pool if p not in used]
        raise ValueError(
            f"port pool exhausted on server {server!r}: no free inbound port on THIS server; "
            f"pool={self.pool}, free={free}. The same numeric ports may still be reused on other servers."
        )


def _tag(text: str) -> str:
    text = re.sub(r"[^A-Za-z0-9_.-]+", "-", text).strip("-")
    return text[:100] or "unnamed"


def _server_reality_settings(listener: Listener, profile: str, fingerprint: str = "chrome") -> dict[str, Any]:
    # IMPORTANT: 3x-ui stores client/share metadata for a REALITY inbound in
    # realitySettings.settings.  The panel's QR/share-link generators read
    # settings.publicKey (not privateKey-derived data) when emitting pbk=.
    # Without this nested object the server itself may run fine, while links
    # generated by 3x-ui contain an empty pbk and clients fail with
    # "REALITY config: empty 'password'".  3x-ui strips this helper object
    # from the runtime server config before passing it to Xray.
    public_key = listener.credentials.public_key
    if not public_key:
        raise ValueError("REALITY public key is empty")
    base: dict[str, Any] = {
        "show": False,
        "target": f"{listener.sni}:443",
        "xver": 0,
        "serverNames": [listener.sni],
        "privateKey": listener.credentials.private_key,
        # Xray-core >= 26.7.11 defaults REALITY minClientVer to 26.3.27.
        # sing-box/Throne REALITY currently identifies itself as 1.8.1, so
        # the default rejects otherwise-valid clients with
        # "reality verification failed".  Explicit compatibility floor is
        # required for mixed Xray + sing-box clients.
        "minClientVer": "0.0.0",
        "shortIds": [listener.credentials.short_id],
        "settings": {
            "publicKey": public_key,
            "fingerprint": fingerprint,
            "serverName": listener.sni,
            "spiderX": "/",
            "mldsa65Verify": "",
        },
    }
    if profile == "legacy":
        # Older configs commonly used dest instead of target.
        base["dest"] = base.pop("target")
    return base


def _client_reality_settings(listener: Listener, fingerprint: str, profile: str) -> dict[str, Any]:
    # Xray renamed REALITY client field `publicKey` to `password`.
    # Current Xray requires `password` and silently ignores the legacy name,
    # while old Xray builds understand `publicKey`.  Emit both so one config
    # works across mixed old/new 3x-ui nodes and modern desktop clients.
    key = listener.credentials.public_key
    if not key:
        raise ValueError("REALITY public key is empty")
    return {
        "serverName": listener.sni,
        "fingerprint": fingerprint,
        "shortId": listener.credentials.short_id,
        "spiderX": "/",
        "password": key,
        "publicKey": key,
    }


def _stream_server(listener: Listener, topo: Topology, transport: str | None = None) -> dict[str, Any]:
    transport = transport or listener.transport or topo.transport
    if transport == "xhttp":
        return {
            "network": "xhttp",
            "security": "reality",
            "xhttpSettings": {
                "host": listener.sni,
                "path": listener.xhttp_path,
                "mode": topo.xhttp_mode,
                "xPaddingBytes": topo.xhttp_padding,
                "headers": {},
            },
            "realitySettings": _server_reality_settings(listener, topo.profile, topo.fingerprint),
        }
    if topo.profile == "modern":
        return {
            "method": "raw",
            "security": "reality",
            "rawSettings": {"header": {"type": "none"}},
            "realitySettings": _server_reality_settings(listener, topo.profile, topo.fingerprint),
        }
    return {
        "network": "tcp",
        "security": "reality",
        "tcpSettings": {"header": {"type": "none"}},
        "realitySettings": _server_reality_settings(listener, topo.profile, topo.fingerprint),
    }


def _stream_client(listener: Listener, fingerprint: str, topo: Topology, transport: str | None = None) -> dict[str, Any]:
    transport = transport or listener.transport or topo.transport
    if transport == "xhttp":
        return {
            "network": "xhttp",
            "security": "reality",
            "xhttpSettings": {
                "host": listener.sni,
                "path": listener.xhttp_path,
                "mode": topo.xhttp_mode,
                "xPaddingBytes": topo.xhttp_padding,
                "headers": {},
            },
            "realitySettings": _client_reality_settings(listener, fingerprint, topo.profile),
        }
    if topo.profile == "modern":
        return {
            "method": "raw",
            "security": "reality",
            "rawSettings": {"header": {"type": "none"}},
            "realitySettings": _client_reality_settings(listener, fingerprint, topo.profile),
        }
    return {
        "network": "tcp",
        "security": "reality",
        "tcpSettings": {"header": {"type": "none"}},
        "realitySettings": _client_reality_settings(listener, fingerprint, topo.profile),
    }


def _flow_for_listener(listener: Listener, transport: str) -> str:
    """Use Vision only for direct client TCP entry profiles.

    Inter-server hops deliberately use standard VLESS-over-REALITY with an
    empty flow. This is more tolerant of mixed Xray generations (especially
    legacy 3x-ui nodes) while keeping the public TCP entry optimized with
    XTLS Vision. XHTTP never uses Vision.
    """
    if transport == "xhttp":
        return ""
    return "xtls-rprx-vision" if listener.source == "client" else ""


def _vless_inbound(listener: Listener, tag: str, topo: Topology, transport: str | None = None) -> dict[str, Any]:
    transport = transport or listener.transport or topo.transport
    user = {
        "id": listener.credentials.uuid,
        "flow": _flow_for_listener(listener, transport),
    }
    settings: dict[str, Any] = {"decryption": "none"}
    if topo.profile == "modern" and transport != "xhttp":
        settings["users"] = [user]
    else:
        user["encryption"] = "none"
        settings["clients"] = [user]
    return {
        "listen": "0.0.0.0",
        "port": listener.port,
        "protocol": "vless",
        "tag": tag,
        "settings": settings,
        "streamSettings": _stream_server(listener, topo, transport),
    }


def _vless_outbound(listener: Listener, target_ip: str, tag: str, fingerprint: str, topo: Topology, transport: str | None = None) -> dict[str, Any]:
    transport = transport or listener.transport or topo.transport
    flow = _flow_for_listener(listener, transport)
    if topo.profile == "modern" and transport != "xhttp":
        settings: dict[str, Any] = {
            "address": target_ip,
            "port": listener.port,
            "id": listener.credentials.uuid,
            "encryption": "none",
            "flow": flow,
        }
    else:
        settings = {
            "vnext": [
                {
                    "address": target_ip,
                    "port": listener.port,
                    "users": [
                        {
                            "id": listener.credentials.uuid,
                            "encryption": "none",
                            "flow": flow,
                        }
                    ],
                }
            ]
        }
    return {
        "protocol": "vless",
        "tag": tag,
        "settings": settings,
        "streamSettings": _stream_client(listener, fingerprint, topo, transport),
    }


def _share_uri(listener: Listener, server_ip: str, topo: Topology, label: str, transport: str | None = None) -> str:
    transport = transport or listener.transport or topo.transport
    if transport == "xhttp":
        extra = json.dumps({
            "headers": {"User-Agent": "Mozilla/5.0"},
            "mode": topo.xhttp_mode,
            "xPaddingBytes": topo.xhttp_padding,
        }, separators=(",", ":"))
        query = (
            f"encryption=none&security=reality&pbk={quote(listener.credentials.public_key)}"
            f"&fp={quote(topo.fingerprint)}&sni={quote(listener.sni)}"
            f"&sid={quote(listener.credentials.short_id)}&type=xhttp"
            f"&host={quote(listener.sni)}&path={quote(listener.xhttp_path)}"
            f"&mode={quote(topo.xhttp_mode)}&x_padding_bytes={quote(topo.xhttp_padding)}"
            f"&extra={quote(extra)}"
        )
    else:
        query = (
            f"type=tcp&security=reality&pbk={quote(listener.credentials.public_key)}"
            f"&fp={quote(topo.fingerprint)}&sni={quote(listener.sni)}"
            f"&sid={quote(listener.credentials.short_id)}&flow=xtls-rprx-vision"
        )
    return f"vless://{listener.credentials.uuid}@{server_ip}:{listener.port}?{query}#{quote(label)}"



def _shadowsocks_inbound(listener: Listener, tag: str) -> dict[str, Any]:
    # Classic AEAD Shadowsocks is intentionally used for mixed/legacy Xray
    # compatibility.  It is encrypted/authenticated and predates the newer
    # SS2022 key-format differences that older 3x-ui/Xray builds may not know.
    return {
        "listen": "0.0.0.0",
        "port": listener.port,
        "protocol": "shadowsocks",
        "tag": tag,
        "settings": {
            "network": "tcp",
            "method": "aes-256-gcm",
            "password": listener.ss_password,
        },
        "streamSettings": {},
    }


def _shadowsocks_outbound(listener: Listener, target_ip: str, tag: str) -> dict[str, Any]:
    return {
        "protocol": "shadowsocks",
        "tag": tag,
        "settings": {
            "address": target_ip,
            "port": listener.port,
            "method": "aes-256-gcm",
            "password": listener.ss_password,
        },
    }

def _direct_outbound(block_private: bool) -> dict[str, Any]:
    if block_private:
        return {
            "tag": "direct",
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "AsIs",
                "finalRules": [
                    {"action": "block", "ip": ["geoip:private"]},
                    {"action": "allow"},
                ],
            },
        }
    return {"tag": "direct", "protocol": "freedom", "settings": {"domainStrategy": "AsIs"}}


def _base_config(topo: Topology) -> dict[str, Any]:
    routing_rules: list[dict[str, Any]] = []
    if topo.block_private:
        routing_rules.append({"type": "field", "ip": ["geoip:private"], "outboundTag": "blocked"})
    if topo.block_bittorrent:
        routing_rules.append({"type": "field", "protocol": ["bittorrent"], "outboundTag": "blocked"})
    return {
        "log": {"loglevel": "warning"},
        "inbounds": [],
        "outbounds": [_direct_outbound(topo.block_private), {"tag": "blocked", "protocol": "blackhole", "settings": {}}],
        "routing": {"domainStrategy": "AsIs", "rules": routing_rules},
    }


def _pick_sni(topo: Topology) -> str:
    return secrets.choice(topo.sni_pool)


def build(
    topo: Topology,
    occupied_ports: dict[str, set[int]] | None = None,
    preferred_ports: dict[str, list[int]] | None = None,
    credential_factory: Callable[[str], RealityCredentials] | None = None,
) -> tuple[dict[str, dict[str, Any]], dict[str, Any], dict[str, dict[str, Any]]]:
    """Return (server_configs, manifest, client_profiles).

    Ports are allocated independently per destination server.  Therefore port
    443 can be used simultaneously on entry, middle and exit.  Only two
    listeners on the *same* server must have different ports.
    """
    topo.validate()
    servers = topo.server_map()
    configs = {name: _base_config(topo) for name in servers}
    clients: dict[str, dict[str, Any]] = {}
    allocator = PortAllocator(topo.port_pool, occupied_ports, preferred_ports)
    manifest_routes: list[dict[str, Any]] = []
    inter_protocol = topo.inter_server_protocol if topo.inter_server_protocol != "auto" else "reality"

    def make_listener(server_name: str, route_index: int, hop_index: int, source: str, transport: str) -> Listener:
        return Listener(
            server=server_name,
            port=allocator.alloc(server_name),
            route_index=route_index,
            hop_index=hop_index,
            source=source,
            transport=transport,
            credentials=(credential_factory(server_name) if credential_factory else generate_reality_credentials()),
            sni=_pick_sni(topo),
            xhttp_path="/" + secrets.token_hex(8),
            ss_password=secrets.token_urlsafe(32),
        )

    for route_index, route in enumerate(topo.routes, start=1):
        route_name = f"route-{route_index:02d}"
        listeners: list[Listener] = []

        # The main chain has one receiver per server.  With dual_entry enabled,
        # the route entry always exposes XHTTP as the primary client receiver,
        # while inter-server receivers keep the selected topology transport.
        for hop_index, server_name in enumerate(route):
            source = "client" if hop_index == 0 else route[hop_index - 1]
            transport = "xhttp" if (hop_index == 0 and topo.dual_entry) else topo.transport
            listeners.append(make_listener(server_name, route_index, hop_index, source, transport))

        entry_listeners: list[Listener] = [listeners[0]]
        if topo.dual_entry:
            # Separate port/credentials are required because two Xray inbounds
            # cannot bind the same port on the same host.  Other servers are
            # independent and may reuse either port from the same pool.
            entry_listeners.append(make_listener(route[0], route_index, 0, "client", "tcp"))

        # Compute the next-hop outbound once per chain node.  Both entry
        # inbounds route to the same outbound, so XHTTP and TCP clients enter
        # the exact same cascade after the first server.
        node_out_tags: list[str] = []
        for hop_index, listener in enumerate(listeners):
            if hop_index + 1 < len(route):
                next_listener = listeners[hop_index + 1]
                next_server = servers[next_listener.server]
                out_tag = _tag(f"cascade-{topo.cascade_id}-out-{route_name}-to-{next_listener.server}")
                if inter_protocol == "shadowsocks":
                    configs[listener.server]["outbounds"].append(
                        _shadowsocks_outbound(next_listener, next_server.ip, out_tag)
                    )
                else:
                    configs[listener.server]["outbounds"].append(
                        _vless_outbound(next_listener, next_server.ip, out_tag, topo.fingerprint, topo, next_listener.transport)
                    )
            else:
                out_tag = "direct"
            node_out_tags.append(out_tag)

        # Entry: one or two client-facing inbounds.
        for entry_listener in entry_listeners:
            suffix = "xhttp" if entry_listener.transport == "xhttp" else "tcp"
            in_tag = _tag(f"cascade-{topo.cascade_id}-in-{route_name}-from-client-{suffix}")
            configs[entry_listener.server]["inbounds"].append(
                _vless_inbound(entry_listener, in_tag, topo, entry_listener.transport)
            )
            configs[entry_listener.server]["routing"]["rules"].append({
                "type": "field",
                "inboundTag": [in_tag],
                "outboundTag": node_out_tags[0],
            })

        # Internal receivers start at hop 1; the first receiver was installed
        # above as the client-facing entry.
        for hop_index, listener in enumerate(listeners[1:], start=1):
            in_tag = _tag(f"cascade-{topo.cascade_id}-in-{route_name}-from-{listener.source}")
            if inter_protocol == "shadowsocks":
                configs[listener.server]["inbounds"].append(
                    _shadowsocks_inbound(listener, in_tag)
                )
            else:
                configs[listener.server]["inbounds"].append(
                    _vless_inbound(listener, in_tag, topo, listener.transport)
                )
            configs[listener.server]["routing"]["rules"].append({
                "type": "field",
                "inboundTag": [in_tag],
                "outboundTag": node_out_tags[hop_index],
            })

        # Client profiles + share URIs for every supported entry transport.
        client_entries: list[dict[str, Any]] = []
        first_server = servers[route[0]]
        for entry_listener in entry_listeners:
            transport = entry_listener.transport
            suffix = "xhttp" if transport == "xhttp" else "tcp"
            profile_name = f"{route_name}-{suffix}" if topo.dual_entry else route_name
            client_out = _vless_outbound(entry_listener, first_server.ip, "proxy", topo.fingerprint, topo, transport)
            clients[profile_name] = {
                "log": {"loglevel": "warning"},
                "inbounds": [
                    {"listen": "127.0.0.1", "port": 10808, "protocol": "socks", "tag": "socks-in", "settings": {"udp": True}}
                ],
                "outbounds": [client_out, {"tag": "direct", "protocol": "freedom"}],
                "routing": {"domainStrategy": "AsIs", "rules": []},
            }
            client_entries.append({
                "transport": transport,
                "server": entry_listener.server,
                "ip": first_server.ip,
                "port": entry_listener.port,
                "uuid": entry_listener.credentials.uuid,
                "sni": entry_listener.sni,
                "short_id": entry_listener.credentials.short_id,
                "public_key": entry_listener.credentials.public_key,
                "uri": _share_uri(entry_listener, first_server.ip, topo, f"{route_name}-{suffix}", transport),
                "profile": profile_name,
            })

        manifest_routes.append({
            "name": route_name,
            "path": route,
            # Keep client_entry for backward compatibility; XHTTP is primary
            # when dual_entry is enabled.
            "client_entry": client_entries[0],
            "client_entries": client_entries,
            "hops": [
                {
                    "from": "client" if i == 0 else route[i - 1],
                    "to": listener.server,
                    "ip": servers[listener.server].ip,
                    "port": listener.port,
                    "sni": listener.sni,
                    "uuid": listener.credentials.uuid,
                    "short_id": listener.credentials.short_id,
                    "public_key": listener.credentials.public_key,
                    "transport": listener.transport,
                    "protocol": "vless" if i == 0 else inter_protocol,
                }
                for i, listener in enumerate(listeners)
            ],
        })

    manifest = {
        "generator": "config-generator",
        "profile": topo.profile,
        "transport": topo.transport,
        "inter_server_protocol": inter_protocol,
        "dual_entry": topo.dual_entry,
        "cascade_id": topo.cascade_id,
        "servers": [{"name": s.name, "ip": s.ip} for s in topo.servers],
        "port_pool": topo.port_pool,
        "port_allocation_scope": "per-server",
        "routes": manifest_routes,
        "notes": [
            "Port allocation is per server: the same numeric port may be reused on different VPS hosts.",
            "Dual entry exposes both VLESS+REALITY+XHTTP and VLESS+REALITY+TCP/RAW on the first server.",
            "Both entry inbounds route into the same next-hop cascade outbound.",
            "Inter-server protocol is selected independently from the public entry transport.",
            "When Shadowsocks is selected, internal hops use encrypted aes-256-gcm for legacy compatibility.",
            "REALITY private keys are used only by VLESS/REALITY receivers.",
            "REALITY private keys are present only in the corresponding server JSON files.",
        ],
    }
    return configs, manifest, clients


def write_output(topo: Topology, output_dir: Path) -> dict[str, Any]:
    configs, manifest, clients = build(topo)
    output_dir.mkdir(parents=True, exist_ok=True)
    servers_dir = output_dir / "servers"
    clients_dir = output_dir / "clients"
    servers_dir.mkdir(exist_ok=True)
    clients_dir.mkdir(exist_ok=True)

    for name, config in configs.items():
        (servers_dir / f"{name}.json").write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    for name, profile in clients.items():
        (clients_dir / f"{name}.json").write_text(json.dumps(profile, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (output_dir / "topology.json").write_text(json.dumps(topo.to_dict(include_secrets=False), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (output_dir / "ROUTES.txt").write_text(render_routes(manifest), encoding="utf-8")
    return manifest


def render_routes(manifest: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("XRAY CASCADE ROUTES")
    lines.append("=" * 72)
    lines.append("Port allocation: PER SERVER (same port may be reused on different VPS hosts)")
    for route in manifest["routes"]:
        lines.append(f"\n{route['name']}: " + " -> ".join(route["path"]) + " -> Internet")
        lines.append("-" * 72)
        for hop in route["hops"]:
            lines.append(
                f"{hop['from']:>12} -> {hop['to']:<16} "
                f"{hop['ip']}:{hop['port']}  protocol={hop.get('protocol','vless')}  SNI={hop['sni']}  transport={hop.get('transport','?')}"
            )
        entries = route.get("client_entries") or [route["client_entry"]]
        lines.append("client entry links:")
        for entry in entries:
            lines.append(
                f"  [{str(entry.get('transport','?')).upper():<5}] "
                f"{entry['ip']}:{entry['port']}  {entry['uri']}"
            )
    lines.append("")
    return "\n".join(lines)

